Fix find your talent page header
bisonaide-org/whakaako-website-react pull request #42
Opened 2024-01-19 17:33 UTC by ilkaytech

### Desciription

- For Companies Page header button fixed
- Navbar support us button is navigated
- Checkout component companies image is navigated

2024-01-19 17:52 UTC, sabata06 commented on src/components/header/header.tsx
> +              className="px-4 py-2 text-sm font-semibold font-display rounded-lg border-2 text-white border-cyan hover:text-gray-900 focus:text-gray-900 hover:bg-gray-200 focus:bg-gray-200 focus:outl
it seems good

2024-01-21 20:52 UTC, busratok requested changes

2024-01-21 20:52 UTC, busratok commented on src/components/header/header.tsx
>            {/* Jump to How It Works component when it is ready */}
```suggestion
```

2024-01-21 20:59 UTC, busratok approved these changes

2024-01-21 20:59 UTC, merged